trigger:
- main 
pool: 
  name: "Dengene-Agent"
variables:
    buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration  $(buildConfiguration)
  displayName: "dot net build $(buildConfiguration)"